/opt/home_surveillance_project/data/storage/*.log
/opt/home_surveillance_project/data/storage/*.err {
    daily
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    copytruncate
    create 0640 surveillance surveillance
}
